### ISSUE TITLE
hpfeeds output plugin

### ISSUE THREAD

**Issue by micheloosterhof** [CommunityHoneyNetwork/cowrie#25]
Hi! I see you made extensions to the hpfeeds output plugin.
If you want, you can send a PR and I can merge them in the main cowrie project.
I won't copy it myself because your plugin is LGPL and doesn't match Cowrie's license. 
But if you are willing to change that, I'm happy to take any updates,

**Comment by JesseBowling** [comment]
Closing this issue as we're moving to hpfeeds3...
